---
title: "Proposal"
output: word_document
bibliography: C:/Users/rober/Documents/GitHub/independent_study/docs/prosody.bib
csl: C:/Users/rober/Documents/GitHub/independent_study/docs/apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Although the analysis of Spanish varieties is well underway in many linguistic domains, there remain gaps in the literature, especially in growing fields like intonational phonology. Through the Autosegmental-Metrical (AM) approach, proposed and developed by researchers like @pierrehumbert1990meaning and @ladd2008intonational, there have been swaths of progress across the hispanic world. Although originally focused primarily on Iberian varieties because of self-reported opportunistic data [@armstrong2014intonational], there has been more recent progress in other varieties of Spanish in Latin America including Dominican, Puerto Rican, Venezuelan, Ecuadorian, Chilean, Argentinian, and Mexican, and Nicaraguan varieties [included in @prieto2010transcription; @chappell2013intonational for Nicaraguan Spanish]. To date, there has been no satisfactory intonational analysis of Salvdoran Spanish varieties within the AM framework.

There is little work available on Salvadoran intonation, especially within the AM framework, or Salvadoran Spanish at all. @azcunaga2004atlas provides linguistic maps of El Salvador, identifying various phonological features of each region, divided further by gender and age. @toledo2007fonologia attempts to review the tonal alignment of the taxonomy presented in previous works by analyzing Salvadoran radiotalk, but the conclusions are unclear. @gamboaanalisis also works within the AM framework to investigate declaratives and interrogatives in speakers from San Salvador. Of interest, she finds that the contours varied by gender: within declarative utterances, H+H\* contours were found for women and L\*+L\* contours for men. However, the methodologies are unclear and the figures included do not allow for reanalysis of the contours.

The proposed study is inspired by the findings of @gamboaanalisis, that there is a distinct variation by gender in Salvadoran Spanish intonation. Although there has been work on gender variation in intonation in English varieties, little work has been seen in Spanish. @enbe2008sociolinguistic investigates Argentinian Spanish and finds that women "prefer the marked prestigious prosodic forms", whereas men "have more random prosodic patterns." These findings are in line with Labovian approaches seen in other research published on English [@lowry2011belfast] that claim that women lead linguistic change and are supposedly more status conscious than men [@labov2001principles]. 

The proposed study will attempt to position itself within the Labovian sociolinguistic framework, as well as the Third Wave framework proposed by @eckert2008variation. Eckert proposes that speaker variation can be represented by indexical fields, "constellation[s] of ideologically related meanings", any part of which can be activated in a given context to give meaning to variables. This is to say, instead of being representative of the demographic itself, the meaning of a variable is only indirectly related to the demographic through context dependent characteristics associated with the category.

@prieto2001entonacio proposed a novel means of collecting intonational data by proposing a Discourse Completion Task intended to elicit particular utterance types that are used in conjunction with specific intonation contours such as statements, yes-no questions, wh- questions, echo questions, imperatives, and vocatives. Originally produced for Catalan, the methodology has been adapted into a number of languages, including Spanish [@prieto_borràs-comes_roseano_2010]. The Spanish survey is further adapted into a number of Spanish varieties and will have to be adapted into the Salvadoran variety for this case, localizing vocabulary and morpho-syntax.

To analyze the data collected, the Tones and Break Indices (ToBI) framework will be used. Within the AM framework, ToBI has been used to annotate intonation because it provides a desirable relationship between phonology and phonetics not found in other annotation systems. Developped originally for Mainstream American English [@beckman1994tobi], it has quickly expanded to be used in other languages. Of note, Spanish ToBI (Sp_ToBI) was proposed and revised by a number of researchers [@vilaplana2008notacion, among others]. Although there is a Sp_ToBI generalized for all Spanish varieties, it has been argued by @ladd2008intonational that each variety of a language would necessitate a separate ToBI system that can be used to compare across variations as well as across languages. This study would contribute both to a general understanding of Sp_ToBI as well as a specific variety of Spanish previously unstudied in mainstream literature.

This study will situate its findings within other studies that have investigated geographically proximal varieties of Spanish: Nicaraguan Spanish [@chappell2013intonational], Puerto Rican Spanish [@armstrong2010puerto], and Dominican Spanish [@willis2010dominican]. When compared, these three varieties have commanlities in their intonation contours, but there are a number of differences. For example, @armstrong2010puerto reports a difference in nuclear configurations between inner and outer negation questions that @chappell2013intonational does not find. @chappell2013intonational demonstrates, however, that the nuclear configurations among interrogatives for these three varieties are overall quite similar, suggesting a relationship between Nicaraguan Spanish and the Caribbean varieties that has been seen in other areas of phonology (such as -s deletion). Situating Salvadoran Spanish within these varieties would be ideal to observe how geographic distance may impact similarities between these varieties; one may expect that Salvadoran Spanish will pattern more like Nicaraguan Spanish and less like the two Caribbean varieties because of geographic proximity.

In sum, there are a number of goals to this study that would help to progress intonational phonology. This study will primarily contribute to Sp_ToBI by continuing to give evidence for universal intonation patterns of Spanish, as well as demonstrate specifics to a singular variety of the language that has not been properly studied in the mainstream literature. This study will also provide information about gender's impact on intonation in Spanish, a topic that has had little exposure within the AM framework. Despite focusing on a small population, this topic will reveal important information about intonation across varieties and across gender.

# References
